"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { BookOpen, Plus, Save, Trash2 } from "lucide-react";
import { ws } from "@/lib/wsclient";
import { useWorkspace } from "@/components/WorkspaceProvider";
import { Empty, PageTitle } from "@/components/ui";

type Skill={id:string;name:string;category:string;courseRefs:string[]};
type Course={id:number;idnumber:string;name:string;shortname:string;visible:boolean;modules:number;linked?:boolean};
type Pos={id:string;name:string;department:string;level:number};
type Data={revision:number;skills:Skill[];courses:Course[];positions:Pos[];matrix:Record<string,Record<string,number>>};
type EditSkill={id:string;name:string;category:string;courses:string[]};
export default function HRContent(){
 const{wsData}=useWorkspace();const searchParams=useSearchParams();const requestedPosition=searchParams.get("position")||"";const requestedSkill=searchParams.get("skill")||"";const[data,setData]=useState<Data|null>(null);const[skills,setSkills]=useState<EditSkill[]>([]);const[matrix,setMatrix]=useState<Record<string,Record<string,number>>>({});const[saving,setSaving]=useState(false);const[msg,setMsg]=useState("");const[selected,setSelected]=useState("");
 useEffect(()=>{if(wsData?.capabilities?.hr)ws<Data>("hr_workspace",{scope:"learning"}).then(d=>{setData(d);setSkills(d.skills.map(s=>({id:s.id,name:s.name,category:s.category,courses:s.courseRefs||[]})));setMatrix(d.matrix||{});setSelected(requestedPosition&&d.positions.some(p=>p.id===requestedPosition)?requestedPosition:"")})},[wsData,requestedPosition]);
 useEffect(()=>{if(!requestedSkill)return;const id=requestAnimationFrame(()=>document.getElementById(`skill-${requestedSkill}`)?.scrollIntoView({behavior:"smooth",block:"center"}));return()=>cancelAnimationFrame(id)},[requestedSkill,data]);
 if(wsData&&!wsData.capabilities?.hrManage&&!wsData.capabilities?.admin)return <Empty title="Нет доступа" text="Редактор обучения доступен HR с правом управления или USTAR Superadmin." mascot/>; if(!data)return <Empty title="Открываем конструктор" text="Читаем реальные Moodle-курсы и модель навыков USTAR…" mascot/>;
 const courses=data.courses.filter(c=>c.idnumber);const row=matrix[selected]||{};const patch=(i:number,v:Partial<EditSkill>)=>setSkills(skills.map((s,j)=>j===i?{...s,...v}:s));
 const save=async()=>{setSaving(true);setMsg("");try{await ws("hr_save_learning",{skillsjson:JSON.stringify(skills),matrixjson:JSON.stringify(matrix),expectedversion:data.revision});const refreshed=await ws<Data>("hr_workspace",{scope:"learning"});setData(refreshed);setSkills(refreshed.skills.map(s=>({id:s.id,name:s.name,category:s.category,courses:s.courseRefs||[]})));setMatrix(refreshed.matrix||{});setMsg("Модель сохранена. Опубликованный стандарт должности обновляется отдельно в её карточке.");}catch(e){setMsg(e instanceof Error?e.message:"Ошибка");}finally{setSaving(false)}};
 return <><PageTitle kicker="USTAR HR · Content Studio" title="Навыки и обучение" subtitle="HR наполняет предметную модель: навык → Moodle-курсы → требования должности. Сами уроки остаются в Moodle, USTAR показывает их в едином опыте."/>
 <div className="mb-4 flex flex-wrap gap-2"><Link href="/hr/workspace" className="btn btn-quiet">← Workspace</Link><a href={`${process.env.NEXT_PUBLIC_MOODLE_URL||"https://158-160-29-94.nip.io"}/course/management.php`} target="_blank" className="btn btn-quiet"><BookOpen size={16}/>Открыть Moodle: курсы</a><button className="btn btn-accent" onClick={()=>setSkills([...skills,{id:`skill_${Date.now()}`,name:"Новый навык",category:"Общее",courses:[]}])}><Plus size={16}/>Навык</button></div>
 <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section className="space-y-3"><div className="eyebrow">Навыки и связанные курсы</div>{skills.map((s,i)=><article id={`skill-${s.id}`} key={`${s.id}-${i}`} className={`card p-4 ${requestedSkill===s.id?"ring-2 ring-accent ring-offset-2":""}`}><div className="flex gap-2"><div className="flex-1"><div className="grid gap-2 sm:grid-cols-2"><input className="input font-black" value={s.name} onChange={e=>patch(i,{name:e.target.value})}/><input className="input" value={s.category} onChange={e=>patch(i,{category:e.target.value})} placeholder="Категория"/></div><input className="input mt-2 font-mono text-xs" value={s.id} disabled={data.skills.some(existing=>existing.id===s.id)} onChange={e=>patch(i,{id:e.target.value})}/><div className="mt-3 grid gap-2 md:grid-cols-2">{courses.map(c=><label key={c.id} className={`flex min-h-11 items-center gap-2 rounded-md border px-3 text-xs font-bold ${s.courses.includes(c.idnumber)?"border-brand bg-accentSoft":"border-black/10"}`}><input type="checkbox" checked={s.courses.includes(c.idnumber)} onChange={e=>patch(i,{courses:e.target.checked?[...s.courses,c.idnumber]:s.courses.filter(x=>x!==c.idnumber)})}/><span className="min-w-0 flex-1 truncate">{c.name}</span><span className="font-mono text-[9px] text-mut">{c.idnumber}</span></label>)}</div>{s.courses.filter(ref=>!courses.some(course=>course.idnumber===ref)).map(ref=><button key={ref} type="button" className="mt-2 rounded-md border border-amber-500 px-3 py-2 text-xs" onClick={()=>patch(i,{courses:s.courses.filter(value=>value!==ref)})}>Курс {ref} не найден · убрать связь</button>)}</div>{!data.skills.some(existing=>existing.id===s.id)&&<button className="btn btn-danger !px-3" aria-label="Убрать новый навык" onClick={()=>setSkills(skills.filter((_,j)=>j!==i))}><Trash2 size={16}/></button>}</div></article>)}</section>
 <aside><div className="sticky top-32 card p-4"><div className="eyebrow">Матрица должности</div><select className="input mt-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите должность</option>{data.positions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{selected?<div className="mt-4 space-y-2">{skills.map(s=>{const lvl=row[s.id]||0;return <div key={s.id} className="rounded-md border border-black/10 p-3"><div className="text-sm font-black">{s.name}</div><div className="mt-2 flex gap-1"><button onClick={()=>{const m={...matrix,[selected]:{...row}};delete m[selected][s.id];setMatrix(m)}} className={`h-8 flex-1 rounded border text-xs font-black ${!lvl?"bg-brand text-white":""}`}>—</button>{[1,2,3,4,5].map(x=><button key={x} onClick={()=>setMatrix({...matrix,[selected]:{...row,[s.id]:x}})} className={`h-8 flex-1 rounded border text-xs font-black ${lvl===x?"bg-accent":""}`}>{x}</button>)}</div></div>})}</div>:<p className="mt-4 text-sm text-mut">Выберите должность, чтобы настроить её требования.</p>}</div></aside></div>
 <div className="sticky bottom-4 z-10 mt-5 flex items-center justify-between rounded-xl border border-black/10 bg-white/95 p-3 shadow-lg backdrop-blur"><span className="text-xs font-bold text-mut">{msg||`${skills.length} навыков · ${courses.length} Moodle-курсов с idnumber`}</span><button className="btn btn-primary" disabled={saving} onClick={save}><Save size={16}/>{saving?"Сохраняем…":"Сохранить изменения"}</button></div></>;
}
